const EDIT = (field) => `[EDIT: ${field}]`;
const PORTFOLIO = {
  identity: { handle: EDIT('HANDLE'), name: EDIT('DISPLAY NAME'), role: EDIT('ROLE / FOCUS'), availability: EDIT('AVAILABILITY OR INQUIRY POLICY'), summary: EDIT('APPROVED PUBLIC SUMMARY'), footerNotice: EDIT('RESPONSIBLE-USE NOTICE') },
  labs: { href: '', label: EDIT('LEARNING-LABS URL') },
  skillGroups: [
    { id: 'offensive', title: 'Offensive security', items: [{ name: EDIT('OFFENSIVE-SECURITY CAPABILITY'), evidence: EDIT('SCOPE OR EVIDENCE') }] },
    { id: 'defensive', title: 'Defensive security', items: [{ name: EDIT('DEFENSIVE-SECURITY CAPABILITY'), evidence: EDIT('SCOPE OR EVIDENCE') }] },
    { id: 'cloud', title: 'Cloud and infrastructure security', items: [{ name: EDIT('CLOUD OR INFRASTRUCTURE CAPABILITY'), evidence: EDIT('SCOPE OR EVIDENCE') }] }
  ],
  projects: [{ id: 'project-01', title: EDIT('PROJECT OR RESEARCH TITLE'), status: EDIT('PUBLICATION STATUS'), year: EDIT('YEAR'), summary: EDIT('APPROVED HIGH-LEVEL SCOPE AND OUTCOME'), details: EDIT('OPTIONAL APPROVED TECHNICAL DETAILS'), tags: [EDIT('TECHNOLOGY OR TOPIC')], evidence: [{ label: EDIT('PUBLIC EVIDENCE LABEL'), href: '' }] }],
  competitions: [{ competition: EDIT('COMPETITION OR EVENT'), placement: EDIT('RESULT'), category: EDIT('CATEGORY'), year: EDIT('YEAR'), evidence: EDIT('PUBLIC-EVIDENCE NOTE'), href: '' }],
  communityProfiles: [{ label: EDIT('SECURITY PLATFORM OR COMMUNITY'), value: EDIT('PUBLIC PROFILE OR STATUS'), href: '' }],
  certifications: [{ name: EDIT('CERTIFICATION ABBREVIATION'), fullName: EDIT('CERTIFICATION NAME'), issuer: EDIT('ISSUER'), year: EDIT('YEAR'), href: '' }],
  experience: [{ period: EDIT('DATE RANGE'), role: EDIT('ROLE'), organization: EDIT('ORGANIZATION'), description: EDIT('APPROVED HIGH-LEVEL SUMMARY'), href: '' }],
  contacts: [{ label: EDIT('CONTACT CHANNEL'), href: '' }],
  pgp: { enabled: false, armoredKey: '' }
};
const $ = (selector) => document.querySelector(selector);
const THEME_KEY = 'portfolio-theme';
const themeToggle = $('#theme-toggle');
const themeMedia = window.matchMedia('(prefers-color-scheme: dark)');
function storedTheme() { try { const value = localStorage.getItem(THEME_KEY); return value === 'dark' || value === 'light' ? value : null; } catch { return null; } }
function applyTheme(theme, persist = false) { document.documentElement.dataset.theme = theme; themeToggle.textContent = `[ theme: ${theme} ]`; themeToggle.setAttribute('aria-pressed', String(theme === 'dark')); themeToggle.setAttribute('aria-label', `Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`); if (persist) { try { localStorage.setItem(THEME_KEY, theme); } catch {} } }
themeToggle.addEventListener('click', () => applyTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark', true));
themeMedia.addEventListener('change', (event) => { if (!storedTheme()) applyTheme(event.matches ? 'dark' : 'light'); });
applyTheme(document.documentElement.dataset.theme === 'light' ? 'light' : 'dark');
const output = $('#terminal-output'); const input = $('#terminal-input'); const dialog = $('#terminal-dialog');
let opener = null; let history = []; let historyIndex = 0;
function node(tag, text = '', className = '') { const el = document.createElement(tag); el.textContent = text; el.className = className; return el; }
function url(value, protocols) { try { const parsed = new URL(value); return protocols.includes(parsed.protocol) ? parsed : null; } catch { return null; } }
function link(label, href, className = '', protocols = ['https:', 'mailto:']) { const parsed = url(href, protocols); if (!parsed) return null; const a = node('a', label, className); a.href = parsed.href; if (parsed.protocol === 'https:') { a.target = '_blank'; a.rel = 'noopener noreferrer'; } return a; }
function placeholder(text, className = 'placeholder') { return node('span', text, className); }
function renderHero() { $('#identity-name').textContent = PORTFOLIO.identity.name; $('#identity-role').textContent = PORTFOLIO.identity.role; $('#identity-summary').textContent = PORTFOLIO.identity.summary; $('#identity-availability').textContent = PORTFOLIO.identity.availability; $('#footer-notice').textContent = PORTFOLIO.identity.footerNotice; const transcript = $('#hero-transcript'); transcript.replaceChildren(node('p', `handle: ${PORTFOLIO.identity.handle}`), node('p', `role: ${PORTFOLIO.identity.role}`), node('p', `status: ${PORTFOLIO.identity.availability}`)); const labs = link(`> ${PORTFOLIO.labs.label}`, PORTFOLIO.labs.href, 'button quiet', ['https:']); const labsTarget = $('#labs-link'); if (labs) labsTarget.replaceWith(labs), labs.id = 'labs-link'; else { labsTarget.removeAttribute('href'); labsTarget.textContent = '> LABS URL REQUIRED'; labsTarget.classList.add('disabled'); } }
let activeSkill = 0;
function renderSkills() { const tabs = $('#skill-tabs'); const panel = $('#skill-panel'); tabs.replaceChildren(); const paint = () => { const group = PORTFOLIO.skillGroups[activeSkill]; panel.replaceChildren(); const title = node('h3', group.title); const list = document.createElement('ul'); group.items.forEach((item) => { const li = document.createElement('li'); li.append(node('strong', item.name), node('span', ` — ${item.evidence}`, 'muted')); list.append(li); }); panel.append(title, list, node('p', `analysis: ${EDIT('REPLACE WITH VERIFIED CONTEXT')}`, 'placeholder')); [...tabs.children].forEach((tab, index) => { tab.setAttribute('aria-selected', String(index === activeSkill)); tab.tabIndex = index === activeSkill ? 0 : -1; }); };
  PORTFOLIO.skillGroups.forEach((group, index) => { const tab = node('button', `[${index + 1}] ${group.title}`, 'skill-tab'); tab.type = 'button'; tab.role = 'tab'; tab.id = `skill-tab-${index}`; tab.setAttribute('aria-controls', 'skill-panel'); tab.addEventListener('click', () => { activeSkill = index; paint(); }); tab.addEventListener('keydown', (event) => { const keys = ['ArrowLeft', 'ArrowRight', 'Home', 'End']; if (!keys.includes(event.key)) return; event.preventDefault(); if (event.key === 'Home') activeSkill = 0; else if (event.key === 'End') activeSkill = PORTFOLIO.skillGroups.length - 1; else activeSkill = (activeSkill + (event.key === 'ArrowRight' ? 1 : -1) + PORTFOLIO.skillGroups.length) % PORTFOLIO.skillGroups.length; paint(); tabs.children[activeSkill].focus(); }); tabs.append(tab); }); panel.role = 'tabpanel'; panel.setAttribute('aria-labelledby', 'skill-tab-0'); paint(); }
function renderProjects() { const grid = $('#project-grid'); grid.replaceChildren(); PORTFOLIO.projects.forEach((project) => { const card = node('article', '', 'card'); card.append(node('p', `[${project.status}] ${project.year}`, 'meta'), node('h3', project.title), node('p', project.summary)); const tags = node('div', '', 'tags'); project.tags.forEach((tag) => tags.append(node('span', `#${tag}`))); card.append(tags); const details = document.createElement('details'); details.append(node('summary', 'Show editable scope')); details.append(node('p', project.details)); project.evidence.forEach((item) => details.append(link(item.label, item.href) || placeholder(item.label))); card.append(details); grid.append(card); }); }
function renderCompetitions() { const body = $('#competition-table-body'); body.replaceChildren(); PORTFOLIO.competitions.forEach((item) => { const row = document.createElement('tr'); [item.competition, item.placement, item.category, item.year].forEach((value) => row.append(node('td', value))); const evidence = document.createElement('td'); evidence.append(link('public link', item.href) || placeholder(item.evidence)); row.append(evidence); body.append(row); }); const profiles = $('#community-profile-grid'); profiles.replaceChildren(); PORTFOLIO.communityProfiles.forEach((item) => { const card = node('article', '', 'card'); card.append(node('h3', item.label), link(item.value, item.href) || placeholder(item.value)); profiles.append(card); }); }
function renderCerts() { const certs = $('#cert-grid'); certs.replaceChildren(); PORTFOLIO.certifications.forEach((item) => { const card = node('article', '', 'card'); card.append(node('h3', item.name), node('p', item.fullName), node('p', `${item.issuer} · ${item.year}`, 'muted'), link('public evidence', item.href) || placeholder(EDIT('PUBLIC EVIDENCE URL'))); certs.append(card); }); const experience = $('#experience-list'); experience.replaceChildren(); PORTFOLIO.experience.forEach((item) => { const row = node('li', '', 'timeline-item'); row.append(node('h3', `${item.period} — ${item.role}`), node('p', item.organization), node('p', item.description, 'muted'), link('public evidence', item.href) || placeholder(EDIT('OPTIONAL PUBLIC EVIDENCE'))); experience.append(row); }); }
function renderContacts() { const contacts = $('#contact-links'); contacts.replaceChildren(); PORTFOLIO.contacts.forEach((item) => { const a = link(item.label, item.href, 'contact-link'); contacts.append(a || placeholder(item.label, 'contact-placeholder')); }); const pgp = $('#pgp-panel'); const key = PORTFOLIO.pgp.armoredKey; if (PORTFOLIO.pgp.enabled && key.includes('-----BEGIN PGP PUBLIC KEY BLOCK-----') && key.includes('-----END PGP PUBLIC KEY BLOCK-----')) { $('#pgp-key').textContent = key; pgp.classList.remove('hidden'); } else pgp.classList.add('hidden'); }
function renderAll() { document.title = `${PORTFOLIO.identity.handle} — Portfolio Draft`; renderHero(); renderSkills(); renderProjects(); renderCompetitions(); renderCerts(); renderContacts(); }
function print(text, type = 'response') { output.append(node('div', text, type)); output.scrollTop = output.scrollHeight; }
function scroll(id) { const target = document.getElementById(id); if (!target) return false; target.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); return true; }
const commands = { help: () => 'Commands: about, skills, projects, project <id>, ctf, certs, contact, labs, open <section>, status, clear, echo <text>, exit', about: () => scroll('about') && 'Opened about.', skills: () => scroll('skills') && 'Opened skills.', projects: () => PORTFOLIO.projects.map((p) => `${p.id} — ${p.title}`).join('\n'), project: (arg) => { const p = PORTFOLIO.projects.find((item) => item.id === arg); return p ? (scroll('projects'), `${p.title}: ${p.summary}`) : 'Unknown project ID.'; }, ctf: () => scroll('ctf') && 'Opened CTF.', certs: () => scroll('certs') && 'Opened certifications.', contact: () => scroll('contact') && 'Opened contact.', labs: () => { const target = url(PORTFOLIO.labs.href, ['https:']); if (!target) return 'Learning-labs URL not configured.'; window.open(target.href, '_blank', 'noopener'); return 'Opened learning labs.'; }, open: (arg) => scroll(arg) ? `Opened ${arg}.` : 'Known sections: about, skills, projects, ctf, certs, contact.', status: () => 'Draft state: replace all [EDIT: ...] fields before public publishing.', clear: () => { output.replaceChildren(); return null; }, echo: (arg) => arg, exit: () => { setTimeout(closeTerminal); return 'Closing terminal.'; } };
function execute(raw) { const [command = '', ...args] = raw.trim().split(/\s+/); print(`visitor@portfolio:~$ ${raw}`, 'command'); const result = commands[command.toLowerCase()] ? commands[command.toLowerCase()](args.join(' ')) : `command not found: ${command}`; if (result !== null && result !== undefined) print(result); }
function openTerminal(source) { opener = source || document.activeElement; dialog.showModal(); if (!output.childElementCount) print('Draft terminal ready. Type help for commands.'); input.focus(); } function closeTerminal() { dialog.close(); opener?.focus(); }
$('#open-terminal').addEventListener('click', (event) => openTerminal(event.currentTarget)); $('#close-terminal').addEventListener('click', closeTerminal); dialog.addEventListener('cancel', (event) => { event.preventDefault(); closeTerminal(); }); dialog.addEventListener('click', (event) => { if (event.target === dialog) closeTerminal(); }); $('#terminal-form').addEventListener('submit', (event) => { event.preventDefault(); const value = input.value.trim(); if (!value) return; execute(value); history.push(value); historyIndex = history.length; input.value = ''; }); input.addEventListener('keydown', (event) => { if (event.key === 'ArrowUp') { event.preventDefault(); if (historyIndex > 0) input.value = history[--historyIndex]; } if (event.key === 'ArrowDown') { event.preventDefault(); if (historyIndex < history.length - 1) input.value = history[++historyIndex]; else input.value = ''; } if (event.key === 'Tab') { event.preventDefault(); const matches = Object.keys(commands).filter((name) => name.startsWith(input.value.trim())); if (matches.length === 1) input.value = `${matches[0]} `; } if (event.ctrlKey && event.key.toLowerCase() === 'l') { event.preventDefault(); output.replaceChildren(); } }); document.addEventListener('keydown', (event) => { if ((event.key === '~' || event.key === '`') && !['INPUT', 'TEXTAREA', 'SELECT'].includes(document.activeElement?.tagName) && !dialog.open) { event.preventDefault(); openTerminal(document.activeElement); } });
function navigation() { if (!('IntersectionObserver' in window)) return; const links = [...document.querySelectorAll('.nav-links a')]; const map = new Map(links.map((a) => [a.hash.slice(1), a])); new IntersectionObserver((entries) => { const active = entries.find((entry) => entry.isIntersecting); if (!active) return; links.forEach((a) => { a.classList.remove('active'); a.removeAttribute('aria-current'); }); const current = map.get(active.target.id); if (current) { current.classList.add('active'); current.setAttribute('aria-current', 'page'); } }, { threshold: .35 }).observe(document.querySelector('#about')); ['skills', 'projects', 'ctf', 'certs', 'contact'].forEach((id) => new IntersectionObserver((entries) => { const active = entries.find((entry) => entry.isIntersecting); if (!active) return; links.forEach((a) => { a.classList.remove('active'); a.removeAttribute('aria-current'); }); const current = map.get(id); current.classList.add('active'); current.setAttribute('aria-current', 'page'); }, { threshold: .35 }).observe(document.querySelector(`#${id}`))); }
renderAll(); navigation();
